spring.application.name=User_Service

# Configuration de la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/USER
spring.datasource.username=postgres
spring.datasource.password=postgres

# Configuration de Hibernate
spring.jpa.hibernate.ddl-auto=update


server.port=8090

