spring.application.name=Security_Service
jwt.secret.key=pQ94nD$w3a8vZPkG1Mq5@LpR&X9!FLJzRkbNhVyWo34
jwt.expiration.time=3600000

user-service.url=http://localhost:8090

server.port=8091

# Configuration de la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Tocken
spring.datasource.username=postgres
spring.datasource.password=postgres

# Configuration de Hibernate
spring.jpa.hibernate.ddl-auto=update


logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.com.example.security_service.service.UserService=DEBUG

