apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.yml: |
    # Configuration Logstash
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline/*
    xpack.monitoring.elasticsearch.hosts: [ "elasticsearch-service:9200" ]
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
data:
  pipeline.conf: |
    input {
      tcp {
        port => 7000
        codec => json
      }
    }

    output {
      elasticsearch {
        hosts => ["elasticsearch-service:9200"]
        index => "springboot-%{app}"
      }
    }
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-service
  labels:
    app: logstash-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash-service
  template:
    metadata:
      labels:
        app: logstash-service
    spec:
      containers:
        - name: logstash-service
          image: logstash:8.15.4
          ports:
            - containerPort: 7000
              protocol: TCP
            - containerPort: 9600
              protocol: TCP
          volumeMounts:
            - name: logstash-config
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
              readOnly: true
            - name: logstash-pipeline
              mountPath: /usr/share/logstash/pipeline
              readOnly: true
          env:
            - name: LS_JAVA_OPTS
              value: "-Xmx256m -Xms256m"
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config
        - name: logstash-pipeline
          configMap:
            name: logstash-pipeline
---

apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  labels:
    app: logstash-service
spec:
  selector:
    app: logstash-service
  ports:
    - name: logstash-tcp
      protocol: TCP
      port: 7000
      targetPort: 7000
    - name: logstash-http
      protocol: TCP
      port: 9600
      targetPort: 9600
  type: LoadBalancer
