apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicule-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicule-service
  template:
    metadata:
      labels:
        app: vehicule-service
    spec:
      containers:
        - name: vehicule-service
          image: vehiculeimage:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: DISCOVERY_SERVICE_URL
              value: http://discovery-service.default.svc.cluster.local:8761/eureka
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 4
---
---
apiVersion: v1
kind: Service
metadata:
  name: vehicule-service
spec:
  selector:
    app: vehicule-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer